/armor_detector:
  ros__parameters:
  # Detector params.
    armor_type_wh_thres: 3
    max_lost_cnt: 5
    max_armors_cnt: 8
    max_v: 8
    max_delta_t: 100
    no_crop_thres: 0.01
    hero_danger_zone: 4
    color: true # red: true
                # blue: false
    no_crop_ratio: 0.002
    full_crop_ratio: 0.0001
    armor_roi_expand_ratio_width: 1.1
    armor_roi_expand_ratio_height: 1.5
    armor_conf_high_thres: 0.82

  # Spinning params.
    anti_spin_judge_high_thres: 20000.0
    anti_spin_judge_low_thres: 2000.0
    anti_spin_max_r_multiple: 4.5
    max_dead_buffer: 2
    max_delta_dist: 0.5
    min_fitting_lens: 10
    shoot_delay: 50
    max_cost: 500
    delta_x_3d_high_thresh: 0.37
    delta_x_3d_higher_thresh: 0.44
    delta_x_3d_low_thresh: 0.23
    delta_x_3d_lower_thresh: 0.15
    delta_x_2d_high_thresh: 65.0
    delta_x_2d_higher_thresh: 85.0
    delta_x_2d_low_thresh: 35.0
    delta_x_2d_lower_thresh: 24.0

  # Camera config params.
    # camera_name: "00J90630561" 
    camera_name: "KE0200110075" 
    camera_type: 0
    camera_param_path: "src/global_user/config/camera.yaml"

  # Network model path.
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-0127-001.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-0527-002.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/1106-333.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/yolox.xml"
    network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-1208-001.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-0127-001.xml"
    save_path: "src/data/infer2_5.txt"

  # Debug params.
    debug: true
    using_imu: false
    using_roi: false
    # draw_predict: true
    show_img: true
    show_fps: true
    print_letency: true
    print_target_info: false
    detect_red: false
    # disable_filter: false
    # disable_fitting: true
    # show_predict: false
    using_shared_memory: false
    show_transformed_info: false
    auto_label: false
    show_all_armors: true
    save_data: true

/armor_processor:
  ros__parameters:
  # Predict params.
    bullet_speed: 28.0
    max_time_delta: 1000
    max_cost: 10
    max_v: 8
    min_fitting_lens: 10
    shoot_delay: 50
    window_size: 3

  # Debug params.
    using_shared_memory: false
    disable_filter: false
    disable_fitting: true
    draw_predict: false
    show_predict: true
    show_transformed_info: false
    debug: true

  # Camera params.
    camera_type: 0 #(daheng: 0 / hik: 1 / mvs: 2 / usb: 3)
    # coord_param_name: "00J90630561" 
    coord_param_name: "KE0200110075" 
    coord_param_path: "src/global_user/config/camera.yaml"
    
  # Filter params.
    filter_param_path: "src/global_user/config/filter_param.yaml"

  # Singer model(--->CS Model).
    singer_alpha: 0.8 # 1/f
    singer_a_max: 0.1
    singer_p_max: 0.1
    singer_p0: 0.8
    singer_dt: 1.0
    singer_sigma: 0.1
    singer_p: 1.0
    singer_r: 1.0
  

    
